export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#0e0e0e",
        "tertiary": "#f3ffca",
        "on-primary-fixed-variant": "#00276b",
        "on-tertiary-container": "#4a5e00",
        "on-secondary": "#3f1000",
        "secondary": "#ff743b",
        "on-tertiary-fixed-variant": "#526900",
        "inverse-on-surface": "#565555",
        "error-dim": "#d7383b",
        "primary-fixed-dim": "#618eff",
        "surface-container": "#1a1a1a",
        "surface": "#0e0e0e",
        "primary-container": "#789dff",
        "tertiary-container": "#cafd00",
        "on-secondary-container": "#fff6f3",
        "on-error-container": "#ffa8a3",
        "surface-dim": "#0e0e0e",
        "on-primary-fixed": "#000000",
        "secondary-fixed": "#ffc4b0",
        "on-secondary-fixed-variant": "#913000",
        "tertiary-fixed": "#cafd00",
        "secondary-dim": "#ff743b",
        "surface-container-lowest": "#000000",
        "on-primary-container": "#001f57",
        "on-tertiary-fixed": "#3a4a00",
        "tertiary-fixed-dim": "#beee00",
        "on-tertiary": "#516700",
        "primary-dim": "#739aff",
        "inverse-primary": "#0e57d0",
        "on-surface-variant": "#adaaaa",
        "surface-container-highest": "#262626",
        "error-container": "#9f0519",
        "surface-container-low": "#131313",
        "surface-tint": "#8dabff",
        "on-error": "#490006",
        "surface-bright": "#2c2c2c",
        "primary": "#8dabff",
        "on-secondary-fixed": "#611d00",
        "tertiary-dim": "#beee00",
        "on-surface": "#ffffff",
        "on-background": "#ffffff",
        "on-primary": "#00296f",
        "surface-container-high": "#20201f",
        "outline-variant": "#484847",
        "error": "#ff716c",
        "secondary-fixed-dim": "#ffb195",
        "inverse-surface": "#fcf9f8",
        "primary-fixed": "#789dff",
        "secondary-container": "#a83900",
        "outline": "#767575",
        "surface-variant": "#262626"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Lexend", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
